In [1]:
from numpy import *
arr = array([2,4,1,5,3])

print(arr.dtype)
print(arr)

int32
[2 4 1 5 3]


In [2]:
from numpy import *
arr = linspace(10,30,6)

print(arr)

[10. 14. 18. 22. 26. 30.]


In [3]:
from numpy import *
arr = arange(1,19,2)

print(arr)

[ 1  3  5  7  9 11 13 15 17]


In [4]:
from numpy import *
arr = logspace(1,40,3)

print(arr)

[1.00000000e+01 3.16227766e+20 1.00000000e+40]


In [5]:
from numpy import *
arr = ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [6]:
from numpy import *
arr = zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [7]:
#add 2 arrays values
from numpy import *
arr = array([2,4,6,7,3])
arr = arr + 6
print(arr)
arr2 = array([2,1,4,2,6])
arr3 = arr + arr2
print(arr3)

[ 8 10 12 13  9]
[10 11 16 15 15]


In [8]:
#math function with numpy

from numpy import *
arr = array([2,4,6,8,9])
print("sin value of each element of array: ",sin(arr)) #to sin walue of each element
print("cos value of each element of array: ",cos(arr)) #to cos walue of each element
print("log value of each element of array: ",log(arr)) #to log walue of each element
print("square value of each element of array: ",square(arr)) #to square walue of each element
print("squareroot value of each element of array: ",sqrt(arr)) #to squareroot walue of each element
print("sum of all elements of array: ",sum(arr)) #to sum all walues
print("to find minimum value from array elements: ",min(arr)) #to find minimum value
print("to find maximum value from array elements: ",max(arr)) #to find maximum value


sin value of each element of array:  [ 0.90929743 -0.7568025  -0.2794155   0.98935825  0.41211849]
cos value of each element of array:  [-0.41614684 -0.65364362  0.96017029 -0.14550003 -0.91113026]
log value of each element of array:  [0.69314718 1.38629436 1.79175947 2.07944154 2.19722458]
square value of each element of array:  [ 4 16 36 64 81]
squareroot value of each element of array:  [1.41421356 2.         2.44948974 2.82842712 3.        ]
sum of all elements of array:  29
to find minimum value from array elements:  2
to find maximum value from array elements:  9


In [9]:
#concatenate function
from numpy import *
arr1 = array([2,4,6,7,3])
arr2 = array([5,3,7,8,3])
print(concatenate([arr1,arr2]))


[2 4 6 7 3 5 3 7 8 3]


In [10]:
#aliasing
from numpy import *
arr1 = array([2,4,6,7,3])

arr2 = arr1

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[2 4 6 7 3]
[2 4 6 7 3]
2240932036400
2240932036400


In [11]:
#shallow copy and   deep copy
#shalow copy-
from numpy import *
arr1 = array([2,4,6,7,3])

arr2 = arr1.view() #shallow copy
#it will copy the elements, but both array depends on each other.
arr1[3] = 5

print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

[2 4 6 5 3]
[2 4 6 5 3]
2240932036000
2240932135920


In [12]:
#shallow copy and   deep copy
#deep copy-
from numpy import *
arr1 = array([2,4,6,7,3])

arr2 = arr1.copy() #deep copy
# it will copy the elements and create two different array,
# two different values, not linked with each other.

arr1[3] = 5

print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))



[2 4 6 5 3]
[2 4 6 7 3]
2240932135120
2240932136000


In [13]:
#to find max value from array without using in built function
from numpy import *
arr1 = array([4,2,1])
if arr1[0]>arr1[1] and arr1[1]>arr1[2]:
    print(arr1[0])
elif arr1[1]>arr1[2]:
    print(arr1[1])
else:
    print(arr1[2])


4


In [14]:
#multi dementional array and attributes
from numpy import *
arr1 = array([
            [5,6,7,8,7,2],
            [3,7,9,2,8,1]
])

print("Type of data in array: ",arr1.dtype) #dtype attribute tells type of array
print("Number of demention: ",arr1.ndim) #it gives number of demention
print("Array has row and colomns(rows,columns): ",arr1.shape)
# it will gives a tuple with value of number of rows and columns in the array.
print("Size of entire block: ",arr1.size) # Size of entire block (number of elements in array)

arr2 = arr1.flatten()#it will flat the 2 dementional array(becomes single dementional array)
print(arr2)


arr3 = arr2.reshape(3,4) #reshape attribute can convert single dementional array into 2d or 3d arrya
# here it convert 2d array
print("after reshape,1D array becomes 2D array\n",arr3)

arr3 = arr2.reshape(2,2,3)
# here it convert 3d array
print("after reshape,1D array becomes 3D array\n",arr3)

Type of data in array:  int32
Number of demention:  2
Array has row and colomns(rows,columns):  (2, 6)
Size of entire block:  12
[5 6 7 8 7 2 3 7 9 2 8 1]
after reshape,1D array becomes 2D array
 [[5 6 7 8]
 [7 2 3 7]
 [9 2 8 1]]
after reshape,1D array becomes 3D array
 [[[5 6 7]
  [8 7 2]]

 [[3 7 9]
  [2 8 1]]]


In [15]:
#matrix and its attributes
from numpy import *
k = matrix('1 3 5 ;2 5 2; 3 5 8') #we can define array like this in matrix
print(k)

print("diagonal values:",diagonal(k)) #it prints diagonal values of matrix.
print("Minimum value of matrix:",k.min()) #it find minimum value of matrix.
print("Maximum value of matrix:",k.max()) #it find maximum value of matrix.


[[1 3 5]
 [2 5 2]
 [3 5 8]]
diagonal values: [1 5 8]
Minimum value of matrix: 1
Maximum value of matrix: 8


In [16]:
#multipy matrix
from numpy import *
k = matrix('1 3 5 ;2 5 2; 3 5 8')
j = matrix('2,5,2 ;4,2,7; 6,2,3')

print(k)
print(j)

l = k * j

print("multiplication of above mentioned arrays: \n",l)

[[1 3 5]
 [2 5 2]
 [3 5 8]]
[[2 5 2]
 [4 2 7]
 [6 2 3]]
multiplication of above mentioned arrays: 
 [[44 21 38]
 [36 24 45]
 [74 41 65]]
