In [3]:
import numpy as np
a5 = np.arange(24).reshape(4,3,2)
a5.shape

(4, 3, 2)

In [5]:
a5 = np.arange(24).reshape(3,2,2,2)
a5

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

# Sciling

In [6]:
arr = np.arange(10)**2
arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
print(arr[0])

0


In [10]:
print(arr[:])

[ 0  1  4  9 16 25 36 49 64 81]


In [12]:
print(arr[-1:-3])

[]


In [13]:
print(arr[-1:-3:-1])

[81 64]


In [14]:
print(arr[-3:-1:-1])

[]


In [15]:
print(arr[-3:-1:1])

[49 64]


In [18]:
print(arr[:-1:-1])

[]


In [22]:
print(arr[::-1])

[81 64 49 36 25 16  9  4  1  0]


In [23]:
print(arr[-4:-4:-1])

[]


In [24]:
print(arr[-4:-5:-1])

[36]


# Slicing in 2D array

In [27]:
student = np.array([['Rocky','Shaggy','Edge','Peter'],[88,90,74,52],[40,86,45,70]])
print(student)

[['Rocky' 'Shaggy' 'Edge' 'Peter']
 ['88' '90' '74' '52']
 ['40' '86' '45' '70']]


In [31]:
print(student.ndim)
print(student.shape)
print(student.size)
print(student.dtype)
print(type(student))

2
(3, 4)
12
<U6
<class 'numpy.ndarray'>


In [32]:
student[0] # in 2d array 0 refers to the first row

array(['Rocky', 'Shaggy', 'Edge', 'Peter'], dtype='<U6')

In [33]:
student[0,1] # 0 index means first row, 1 index means 2nd element of 0 index row.

'Shaggy'

In [34]:
student[0][1]

'Shaggy'

In [35]:
student[2,2] 

'45'

In [41]:
student[:]

array([['Rocky', 'Shaggy', 'Edge', 'Peter'],
       ['88', '90', '74', '52'],
       ['40', '86', '45', '70']], dtype='<U6')

In [42]:
student[2:3,2:3]

array([['45']], dtype='<U6')

In [43]:
print(student[:3,:2])

array([['Rocky', 'Shaggy'],
       ['88', '90'],
       ['40', '86']], dtype='<U6')

In [45]:
print(student[1:1:2,1:1:1])

[]


In [46]:
student[:1,:]

array([['Rocky', 'Shaggy', 'Edge', 'Peter']], dtype='<U6')

In [50]:
student[-1,:]

array(['40', '86', '45', '70'], dtype='<U6')

In [51]:
student[1,:]

array(['88', '90', '74', '52'], dtype='<U6')

In [52]:
student[-3:-1,-1]

array(['Peter', '52'], dtype='<U6')

In [56]:
student[...,2]

array(['Edge', '74', '45'], dtype='<U6')

In [57]:
st = student[...,2] # if we are not performing sciling on columns then output will be 1d array in 2d array.
st.shape

(3,)

In [58]:
st = student[:,1:2] # if we perform sciling on columns then output will be 2d array in 2d array.
st.shape

(3, 1)

In [4]:
randMat = np.random.rand(4,3) # Random matrix with given shape, np.random.random(size=(2,2))
randMat

array([[0.81015993, 0.51894415, 0.15674179],
       [0.37929702, 0.43118789, 0.44127487],
       [0.04821858, 0.3655849 , 0.09350673],
       [0.17653134, 0.13165008, 0.58390669]])

In [60]:
randMat[0,1]

0.9232809894061716

In [61]:
randMat[0:2]

array([[0.6541214 , 0.92328099, 0.18303911],
       [0.65808353, 0.50312822, 0.79232323]])

In [62]:
print(randMat[0],randMat[0,:])

[0.6541214  0.92328099 0.18303911] [0.6541214  0.92328099 0.18303911]


In [63]:
randMat[:,0]

array([0.6541214 , 0.65808353, 0.25352361, 0.52474685])

In [64]:
randMat[1,:]=0
randMat

array([[0.6541214 , 0.92328099, 0.18303911],
       [0.        , 0.        , 0.        ],
       [0.25352361, 0.16952149, 0.84259917],
       [0.52474685, 0.15540289, 0.64761733]])

In [65]:
randMat[0:2]

array([[0.6541214 , 0.92328099, 0.18303911],
       [0.        , 0.        , 0.        ]])

In [10]:
import numpy as np
randMat = np.arange(12).reshape(4,3) # Random matrix with given shape, np.random.random(size=(2,2))
randMat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
randMat[[3,2,1,0]] # Slicing multiple rows at random position.

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [71]:
randMat[0:2,0:2]

array([[0.6541214 , 0.92328099],
       [0.        , 0.        ]])

In [72]:
randMat[-1]

array([0.52474685, 0.15540289, 0.64761733])

In [73]:
randMat[::1,::2]

array([[0.6541214 , 0.18303911],
       [0.        , 0.        ],
       [0.25352361, 0.84259917],
       [0.52474685, 0.64761733]])

# 3-D array

In [74]:
arr3 = np.array([[(1.6,2,3),(4,5,6)],[(3,2,1),(5,5,8)]], dtype = 'int')
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [5, 5, 8]]])

In [75]:
arr3.shape

(2, 2, 3)

In [76]:
arr3.ndim

3

In [77]:
arr3.size

12

In [78]:
arr3.dtype

dtype('int32')

In [79]:
type(arr3)

numpy.ndarray

In [85]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr3[0,1]

array([4, 5, 6])

In [87]:
arr3[0,0]

array([1, 2, 3])

In [92]:
arr3[0,0:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
arr3[0,0:2,:1]

array([[1],
       [4]])

In [94]:
arr3[0,0:2,1]

array([2, 5])

In [95]:
arr3[0][0:2,:1]

array([[1],
       [4]])

In [96]:
arr3[0,1]

array([4, 5, 6])

In [97]:
print(arr3[1][:,1])

[2 5]


In [98]:
student = np.array([['Rocky','Shaggy','Edge','Peter'],[88,90,74,52],[40,86,45,70]])
print(student)

[['Rocky' 'Shaggy' 'Edge' 'Peter']
 ['88' '90' '74' '52']
 ['40' '86' '45' '70']]


In [99]:
a = np.arange(10)**2
for i in a:
    print(i)

0
1
4
9
16
25
36
49
64
81


In [102]:
for i in student:
    for j in i:
        print(j)

Rocky
Shaggy
Edge
Peter
88
90
74
52
40
86
45
70


In [103]:
for i in student.flatten():
    print(i)

Rocky
Shaggy
Edge
Peter
88
90
74
52
40
86
45
70


In [105]:
for i in student.flatten(order='F'):
    print(i)

Rocky
88
40
Shaggy
90
86
Edge
74
45
Peter
52
70


In [ ]:
# create a ndarray 3,4.

In [108]:
arr0 = np.arange(12).reshape(3,4)
arr0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
for i in np.nditer(arr0):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [111]:
for i in np.nditer(arr0,order ='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [113]:
for i in np.nditer(arr0,order ='F',flags =['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [17]:
arr0 = np.arange(12).reshape(3,4)
arr0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
for i in np.nditer(arr0):
    i[...]=i*i
    



ValueError: assignment destination is read-only

In [126]:
for i in np.nditer(arr0,op_flags = ['readwrite']):
    i[...]=i*i
    print(i)
print(arr0)

0
1
4
9
16
25
36
49
64
81
100
121
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [127]:
a = np.array([('Germany','France','Hungary','Austria'),('Berlin','Paris','Budapest','Vienna')],dtype = 'object')

In [128]:
print(a)
print(a.dtype)
print(a.dtype.name)

[['Germany' 'France' 'Hungary' 'Austria']
 ['Berlin' 'Paris' 'Budapest' 'Vienna']]
object
object


In [130]:
a = np.array([('Germany','France','Hungary','Austria'),('Berlin','Paris','Budapest','Vienna')])
print(a.dtype)
print(a.dtype.name)

<U8
str256


## The ravel()

In [131]:
a.ravel()

array(['Germany', 'France', 'Hungary', 'Austria', 'Berlin', 'Paris',
       'Budapest', 'Vienna'], dtype='<U8')

## T gives transpose of an array

In [132]:
a.T

array([['Germany', 'Berlin'],
       ['France', 'Paris'],
       ['Hungary', 'Budapest'],
       ['Austria', 'Vienna']], dtype='<U8')

In [133]:
a.T.ravel()

array(['Germany', 'Berlin', 'France', 'Paris', 'Hungary', 'Budapest',
       'Austria', 'Vienna'], dtype='<U8')

In [134]:
a.shape

(2, 4)

In [135]:
a.reshape(4,2)

array([['Germany', 'France'],
       ['Hungary', 'Austria'],
       ['Berlin', 'Paris'],
       ['Budapest', 'Vienna']], dtype='<U8')

In [136]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [137]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## The reshape() dimension needs to mathc the number of values in the array
### Reshaping a 15 element array to an 18  element one will throw an error

In [138]:
np.arange(15).reshape(3,6)

ValueError: cannot reshape array of size 15 into shape (3,6)

In [139]:
countries = np.array(["Germany","India","USA","Itely","France","Pakistan"])
countries

array(['Germany', 'India', 'USA', 'Itely', 'France', 'Pakistan'],
      dtype='<U8')

In [140]:
countries.reshape(-1,3)

array([['Germany', 'India', 'USA'],
       ['Itely', 'France', 'Pakistan']], dtype='<U8')

In [141]:
countries.reshape(2,-1)

array([['Germany', 'India', 'USA'],
       ['Itely', 'France', 'Pakistan']], dtype='<U8')

In [142]:
countries.reshape(3,-1)

array([['Germany', 'India'],
       ['USA', 'Itely'],
       ['France', 'Pakistan']], dtype='<U8')

### If the values of the dimention are not factors of the number of elements, there will be an error.

In [143]:
countries.reshape(8,-1)

ValueError: cannot reshape array of size 6 into shape (8,newaxis)

In [145]:
x = np.arange(12)
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
randMat

array([[0.6541214 , 0.92328099, 0.18303911],
       [0.        , 0.        , 0.        ],
       [0.25352361, 0.16952149, 0.84259917],
       [0.52474685, 0.15540289, 0.64761733]])

In [146]:

randMat[[0,2,3]] # Slicing multiple rows at random position.

array([[0.6541214 , 0.92328099, 0.18303911],
       [0.25352361, 0.16952149, 0.84259917],
       [0.52474685, 0.15540289, 0.64761733]])

In [149]:
randMat[0,2]

0.1830391063095348